deployment:
  replicas: 1
  strategy:
    type: RollingUpdate
    maxSurge: 1
    maxUnavailable: 1
  containers:
    -
      name: orchestrator
      image:
        repository: flaminel/orchestrator
        tag: latest
      resources:
        requests:
          cpu: 500m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 128Mi
      envFromSecret:
        -
          secretName: connections-secret
          envs:
            -
              name: ConnectionStrings__Orchestrator
              key: orchestratorDb
            -
              name: RabbitMQConfiguration__Host
              key: rabbitMqHost
            -
              name: RabbitMQConfiguration__Username
              key: rabbitMqUser
            -
              name: RabbitMQConfiguration__Password
              key: rabbitMqPassword

secrets:
  -
    name: connections-secret
    type: Opaque
    data:
      orchestratorDb: server=$MySQLHost;port=3306;database=orchestrator;uid=$MySQLUser;pwd='$MySQLPassword';sslMode=Required
      rabbitMqHost: $RabbitMQHost
      rabbitMqUser: $RabbitMQUsername
      rabbitMqPassword: $RabbitMQPassword