on:
  push:
    paths:
      - 'code/**'
    branches: [ main ]

jobs:
  build:
    name: Build
    uses: Flaminel/orchestrator/.github/workflows/build.yml@main
    secrets: inherit

  deploy:
    name: Deploy
    needs: [ build ]
    uses: Flaminel/orchestrator/.github/workflows/deploy.yml@main
    secrets: inherit